server.port=8083

spring.datasource.url=jdbc:postgresql://postgres:5432/transaction_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

account-service.url=http://account-service:8082

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

keycloak.jwk-set-uri=http://host.docker.internal:8180/realms/banking/protocol/openid-connect/certs
keycloak.issuer=http://localhost:8180/realms/banking
