#spring.application.name=transaction-service
#server.port=8083
#
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
## Since services are registered in Eureka, use the service name instead of localhost
#account-service.url=${ACCOUNT_SERVICE_URL:http://account-service:8082}
#
#############################
## Retry
#############################
#resilience4j.retry.instances.accountService.max-attempts=3
#resilience4j.retry.instances.accountService.wait-duration=2s
#
#############################
## Circuit Breaker
#############################
#resilience4j.circuitbreaker.instances.accountService.failure-rate-threshold=50
#resilience4j.circuitbreaker.instances.accountService.minimum-number-of-calls=5
#resilience4j.circuitbreaker.instances.accountService.sliding-window-size=5
#resilience4j.circuitbreaker.instances.accountService.wait-duration-in-open-state=30s
#resilience4j.circuitbreaker.instances.accountService.permitted-number-of-calls-in-half-open-state=2
#
#logging.level.io.github.resilience4j.retry=DEBUG
#logging.level.io.github.resilience4j.circuitbreaker=DEBUG
#
#spring.config.import=optional:configserver:http://config-server:8888
#
#eureka.client.service-url.defaultZone=http://service-registry:8761/eureka
#
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true


spring.application.name=transaction-service

server.port=8083

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/transaction_db
spring.datasource.username=sneha.satish
spring.datasource.password=Valtech@2026

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Config Server
spring.config.import=optional:configserver:http://localhost:8888