spring.application.name=api-gateway

server.port=8080

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true

#//Gateway downloads the service list.
eureka.client.fetch-registry=true

# Enable Discovery Locator
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# Customer Service Route
spring.cloud.gateway.server.webflux.routes[0].id=customer-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://customer-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/customers/**

# Account Service Route
spring.cloud.gateway.server.webflux.routes[1].id=account-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://account-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/accounts/**

# Transaction Service Route
spring.cloud.gateway.server.webflux.routes[2].id=transaction-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://transaction-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/transactions/**