server.port=8081

spring.datasource.url=jdbc:postgresql://postgres:5432/customer_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

keycloak.jwk-set-uri=http://host.docker.internal:8180/realms/banking/protocol/openid-connect/certs
keycloak.issuer=http://localhost:8180/realms/banking

keycloak.url=http://host.docker.internal:8180
keycloak.realm=banking
keycloak.admin.username=admin
keycloak.admin.password=admin
