apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: snehasatish/account-service:v7
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_URL
              value: "jdbc:postgresql://postgres-service:5432/account_db"
            - name: DB_USERNAME
              value: "sneha.satish"
            - name: DB_PASSWORD
              value: "Valtech@2026"
            - name: EUREKA_URL
              value: "http://service-registry:8761/eureka"
