#spring.application.name=account-service
#
#server.port=8082
#
#
##spring.datasource.url=jdbc:postgresql://postgres:5432/banking_db
##spring.datasource.username=sneha.satish
##spring.datasource.password=Valtech@2026
#
#eureka.client.service-url.defaultZone=http://service-registry:8761/eureka
#
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#spring.config.import=optional:configserver:http://config-server:8888