apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  namespace: banking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-service
          image: saniyasyed66/customer-service:k8sfix-160623
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes

            - name: KEYCLOAK_JWK_SET_URI
              value: "http://172.31.0.85:8180/realms/banking/protocol/openid-connect/certs"

            - name: KEYCLOAK_ISSUER
              value: "http://13.203.97.183:8180/realms/banking"

            - name: KEYCLOAK_URL
              value: "http://172.31.0.85:8180"

            - name: DB_PASSWORD
              value: postgres