apiVersion: v1
kind: Service
metadata:
  name: financial-intelligence-service
  namespace: banking
spec:
  selector:
    app: financial-intelligence-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP