apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: banking
data:
  init-db.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
        CREATE DATABASE customer_db;
        CREATE DATABASE account_db;
        CREATE DATABASE transaction_db;
    EOSQL