apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: banking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: saniyasyed66/transaction-service:k8sfix-160623
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: KEYCLOAK_JWK_SET_URI
              value: "http://172.31.0.85:8180/realms/banking/protocol/openid-connect/certs"
            - name: KEYCLOAK_ISSUER
              value: "http://13.203.97.183:8180/realms/banking"
            - name: DB_PASSWORD
              value: postgres