apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service

    spec:
      containers:
        - name: auth-service

          image: chinmayanand5613/auth-service:1.0
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8082

          env:
            - name: DB_URL
              value: jdbc:postgresql://postgres:5432/authdb

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: SPRING_PROFILES_ACTIVE
              value: docker

            - name: CONFIG_SERVER_URL
              value: http://config-server:8888

            - name: EUREKA_URL
              value: http://service-registry:8761/eureka

            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-mail-secret
                  key: MAIL_USERNAME

            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-mail-secret
                  key: MAIL_PASSWORD

            - name: ZIPKIN_ENDPOINT
              value: http://zipkin:9411/api/v2/spans