server.port=8082

spring.datasource.url=jdbc:postgresql://postgres:5432/account_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

customer-service.url=http://customer-service:8081

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

keycloak.jwk-set-uri=http://host.docker.internal:8180/realms/banking/protocol/openid-connect/certs
keycloak.issuer=http://localhost:8180/realms/banking

transaction-service.url=http://transaction-service:8083
internal.call.secret=${INTERNAL_CALL_SECRET:local-dev-internal-secret}
