server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/chinmayanandValtech/banking-config-server.git

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
