spring.application.name=financial-intelligence-service

server.port=8084

# Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

# Transaction Service
transaction-service.url=http://transaction-service:8083

# Keycloak

keycloak.url=http://host.docker.internal:8180
keycloak.realm=banking

keycloak.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://host.docker.internal:8180/realms/banking/protocol/openid-connect/certs}
keycloak.issuer=${KEYCLOAK_ISSUER:http://localhost:8180/realms/banking}