spring.application.name=auth-service

server.port=8084



# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# JWT
jwt.secret=ThisIsMySecretKeyForJwtAuthenticationInBankingApplication9844442726
jwt.expiration=3600000

# Config Server
spring.config.import=optional:configserver:http://config-server:8888