name: Account Service CI

on:
  push:
    branches:
      - chinmay_prod
    paths:
      - 'services/account-service/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/account-service

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Current Directory
        run: pwd

      - name: List Files
        run: ls -la