name: Account Service CI

on:
  push:
    branches:
      - chinmay_prod
    paths:
      - 'services/account-service/**'
      - '.github/workflows/account-service.yml'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/account-service

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Build with Maven
        run: ./mvnw clean package

      - name: Verify Java
        run: |
          java -version
          mvn -version

     
