name: Customer Service CI

on:
  push:
    branches:
      - eureka_try_sneha

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print message
        run: echo "Hello Sneha! Your first CI pipeline is running."