name: Customer Service CI

on:
  push:
    branches:
      - eureka_try_sneha

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build customer-service
        run: |
          cd customer-service
          mvn clean package

      - name: Build Docker image
        run: |
          cd customer-service
          docker build -t customer-service:test .